export enum TableNames {
  casa_matriz = 'casa_matriz',
  clientes = 'clientes',
  detalles_pedidos = 'detalles_pedidos',
  dosificaciones = 'dosificaciones',
  facturas = 'facturas',
  menus = 'menus',
  pagos_pedido = 'pagos_pedido',
  pedidos = 'pedidos',
  productos = 'productos',
  roles = 'roles',
  roles_menus = 'roles_menus',
  roles_usuarios = 'roles_usuarios',
  sucursales = 'sucursales',
  tabla_log = 'tabla_log',
  token_verificacion = 'token_verificacion',
  usuarios = 'usuarios',
  categorias_productos = 'categorias_productos',
  categorias_productos_productos = 'categorias_productos_productos',
  caja = 'cajas',
  movimientos_cajas = 'movimientos_cajas',
}
